% This function calculates the elastic force generated by the spring
% attached in series with each cable, given the cable displacements.

function Fka = CableElasticity(Ck, LinkRadius, DisplacementA, DisplacementB)

% % Cable Displacements
% DisplacementA1short = DisplacementA(1,1);
% DisplacementA2short = DisplacementA(1,2);
% DisplacementA3short = DisplacementA(1,3);
% 
% DisplacementB1short = DisplacementB(1,1);
% DisplacementB2short = DisplacementB(1,2);
% DisplacementB3short = DisplacementB(1,3);

DisplacementA1long = DisplacementA(2,1);
DisplacementA2long = DisplacementA(2,2);
DisplacementA3long = DisplacementA(2,3);

DisplacementB1long = DisplacementB(2,1);
DisplacementB2long = DisplacementB(2,2);
DisplacementB3long = DisplacementB(2,3);

% Spring constants
CkA1 = Ck(1); CkA2 = Ck(2); CkA3 = Ck(3);

% Spring constants for modules A and B are the same
CkB1 = CkA1; CkB2 = CkA2; CkB3 = CkA3;

% % Elastic force, Module A
% FkA1 = -CkA1*(DisplacementA1short+DisplacementA1long);
% FkA2 = -CkA2*(DisplacementA2short+DisplacementA2long);
% FkA3 = -CkA3*(DisplacementA3short+DisplacementA3long);
% 
% % Elastic force, Module B
% FkB1 = -CkB1*(DisplacementB1short+DisplacementB1long);
% FkB2 = -CkB2*(DisplacementB2short+DisplacementB2long);
% FkB3 = -CkB3*(DisplacementB3short+DisplacementB3long);

% Elastic force, Module A
FkA1 = -CkA1*(DisplacementA1long);
FkA2 = -CkA2*(DisplacementA2long);
FkA3 = -CkA3*(DisplacementA3long);

% Elastic force, Module B
FkB1 = -CkB1*(DisplacementB1long);
FkB2 = -CkB2*(DisplacementB2long);
FkB3 = -CkB3*(DisplacementB3long);

% Torques at each joint
TorquekA3 = FkA3*LinkRadius;
TorquekA2 = FkA2*LinkRadius;
TorquekA1 = FkA1*LinkRadius;
Torquek4 = 0;
TorquekB3 = FkB3*LinkRadius;
TorquekB2 = FkB2*LinkRadius;
TorquekB1 = FkB1*LinkRadius;

% Going to generalized coordinates
Fka = [0;0;-TorquekA1/2;0;0;TorquekA1/2-TorquekA2/2;0;0;TorquekA2/2-TorquekA3/2;0;0;TorquekA3/2-Torquek4/2;...
       0;0;Torquek4/2-TorquekB1/2;0;0;TorquekB1/2-TorquekB2/2;0;0;TorquekB2/2-TorquekB3/2;0;0;TorquekB3/2];
   
end
